image: registry.leyantech.com/infra/node:14.15.1-stretch

cache:
  key:
    files:
      - yarn.lock
  paths:
    - node_modules

before_script:
  - yarn install --frozen-lockfile

after_script:
  - cp -r -f build/* public

pages:
  stage: deploy
  tags:
  - docker
  script:
  - yarn build
  artifacts:
    paths:
    - public
  only:
  - master
